---
- name: Check installed packer version
  shell: "packer --version | head -n1 | grep {{ packer_install_version }}"
  failed_when: false
  changed_when: false
  register: installed_packer_version

- name: Check tmp packer version
  shell: "{{ packer_unarchive_destination }}/packer --version | head -n1 | grep {{ packer_install_version }}"
  failed_when: false
  changed_when: false
  register: tmp_packer_version

- name: Debug installed version
  debug:
    msg: "Installed: {{installed_packer_version}}"

- name: Debug tmp version
  debug:
    msg: "Installed: {{tmp_packer_version}}"

- name: Download packer
  get_url:
    url: "{{ packer_releases_url }}"
    dest: "{{ packer_download_destination }}"
  when: installed_packer_version.rc != 0

- name: Create packer unzip dir
  file:
    path: "{{ packer_unarchive_destination }}"
    state: directory
    mode: 0755
  when: installed_packer_version.rc != 0

- name: Unzip packer
  unarchive:
    src: "{{ packer_download_destination }}"
    dest: "{{ packer_unarchive_destination }}"
    copy: no
  when: installed_packer_version.rc != 0 or tmp_packer_version.rc != 0

- name: Move packer for execution
  copy:
    src: "{{ packer_unarchive_destination }}/packer"
    dest: "{{ packer_execution_path }}"
    mode: u+x,g+x,o+x
    remote_src: true
  when: installed_packer_version.rc != 0
