---
- name: Download Packer
  get_url:
    url: "{{ packer_releases_url }}"
    dest: "{{ packer_download_destination }}"

- name: Create Packer unzip dir
  file:
    path: "{{ packer_unarchive_destination }}"
    state: directory
    mode: 0755

- name: Unzip Packer
  unarchive:
    src: "{{ packer_download_destination }}"
    dest: "{{ packer_unarchive_destination }}"
    copy: no
    creates: "{{ packer_unarchive_destination }}/packer"

- name: Move Packer for execution
  copy:
    src: "{{ packer_unarchive_destination }}/packer"
    dest: "{{ packer_execution_path }}"
    mode: u+x,g+x,o+x
    remote_src: true